//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Device : global::System.Configuration.ApplicationSettingsBase {
        
        private static Device defaultInstance = ((Device)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Device())));
        
        public static Device Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.112")]
        public string IP_ADDR_SIGNAL_GEN {
            get {
                return ((string)(this["IP_ADDR_SIGNAL_GEN"]));
            }
            set {
                this["IP_ADDR_SIGNAL_GEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5025")]
        public int PORT_SIGNAL_GEN {
            get {
                return ((int)(this["PORT_SIGNAL_GEN"]));
            }
            set {
                this["PORT_SIGNAL_GEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.111")]
        public string IP_ADDR_POWER_SUP {
            get {
                return ((string)(this["IP_ADDR_POWER_SUP"]));
            }
            set {
                this["IP_ADDR_POWER_SUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5025")]
        public int PORT_POWER_SUP {
            get {
                return ((int)(this["PORT_POWER_SUP"]));
            }
            set {
                this["PORT_POWER_SUP"] = value;
            }
        }
    }
}
