//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareSettings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Network : global::System.Configuration.ApplicationSettingsBase {
        
        private static Network defaultInstance = ((Network)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Network())));
        
        public static Network Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.0")]
        public string IP_ADDRESS_POWER_SUPPLY {
            get {
                return ((string)(this["IP_ADDRESS_POWER_SUPPLY"]));
            }
            set {
                this["IP_ADDRESS_POWER_SUPPLY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5025")]
        public int PORT_POWER_SUPPLY {
            get {
                return ((int)(this["PORT_POWER_SUPPLY"]));
            }
            set {
                this["PORT_POWER_SUPPLY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.1")]
        public string IP_ADDRESS_SOURCE_SIGNAL {
            get {
                return ((string)(this["IP_ADDRESS_SOURCE_SIGNAL"]));
            }
            set {
                this["IP_ADDRESS_SOURCE_SIGNAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5025")]
        public int PORT_SOURCE_SIGNAL {
            get {
                return ((int)(this["PORT_SOURCE_SIGNAL"]));
            }
            set {
                this["PORT_SOURCE_SIGNAL"] = value;
            }
        }
    }
}
